development:
  adapter: postgresql
  encoding: unicode
  database: dbtc_development
  pool: 5
  username: rick
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: dbtc_test
  pool: 5
  username: rick
  password:
